export const galleryGetters = {
  GET_ALL_IMAGES: 'GET_ALL_IMAGES',
  GET_IMAGE_BY_ID: 'GET_IMAGE_BY_ID',
};

export const galleryActions = {
  ADD_IMAGE_TO_GALLERY: 'ADD_IMAGE_TO_GALLERY',
  UPLOAD_IMAGES: 'UPLOAD_IMAGES',
  LIKES_INCREMENTATION: 'LIKES_INCREMENTATION',
  DISLIKES_INCREMENTATION: 'DISLIKES_INCREMENTATION',
  LIKES_DECREMENT: 'LIKES_DECREMENT',
  DISLIKES_DECREMENT: 'DISLIKES_DECREMENT',
  UPDATE_LOCAL_STORAGE: 'UPDATE_LOCAL_STORAGE',
  COMMENT_INCREMENT: 'COMMENT_INCREMENT',
  FLICKR_IMAGES: 'FLICKR_IMAGES',
  DELETE_IMAGE_BY_SRC: 'DELETE_IMAGE_BY_SRC',
};

export const galleryMutations = {
  ADD_LIKE: 'ADD_LIKE',
  ADD_DISLIKE: 'ADD_DISLIKE',
  DELETE_LIKE: 'DELETE_LIKE',
  DELETE_DISLIKE: 'DELETE_DISLIKE',
  ADD_COMMENT: 'ADD_COMMENT',
  FILL_IMAGES: 'FILL_IMAGES',
  ADD_IMAGE: 'ADD_IMAGE',
  DELETE_IMAGE: 'DELETE_IMAGE',
};
