export const popupGetters = {
  GET_UPLOADED_IMAGES: 'GET_UPLOADED_IMAGES',
};

export const popupActions = {
  UPLOAD_IMAGES: 'UPLOAD_IMAGES',
  CLEAR_IMAGES_POPUP: 'CLEAR_IMAGES_POPUP',
  SET_AS_ADDED: 'SET_AS_ADDED',
  SET_AS_DEFAULT: 'SET_AS_DEFAULT',
};

export const popupMutations = {
  RENEW_IMAGES: 'RENEW_IMAGES',
  CLEAR_IMAGES: 'CLEAR_IMAGES',
  SET_AS_ADDED: 'SET_AS_ADDED',
  SET_AS_DEFAULT: 'SET_AS_DEFAULT',
};
